apiVersion: apps/v1
kind: Deployment
metadata:
  name: loom-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dappchain
  template:
    metadata:
      labels:
        app: dappchain
    spec:
      containers:
        - name: node
          image: loomnetwork/loom
